### ISSUE TITLE
Add support for Bluesky

### ISSUE THREAD

**Issue by rxu** [phpbb-extensions/mediaembed#106]
Add Bluesky to keep in sync with the latest text-formatter code.
Possible yaml:
```
name: Bluesky
host: bsky.app
homepage: https://bsky.app/
example: https://bsky.app/profile/jamesgunn.bsky.social/post/3l6kscjixz22q
extract: "!bsky\\.app/profile/(?'name'[A-Za-z0-9.]+)/post/(?'id'\\w+)!"
oembed:
    endpoint: https://embed.bsky.app/oembed
    scheme: [https://bsky.app/profile/{@name}/post/{@id](https://bsky.app/profile/%7B@name%7D/post/%7B@id)}
scrape:
    - extract: "!\"did\":\\s*\"did:(?'did'[a-zA-Z0-9._:%-]+)\"!"
    - match: "//"
    - url: https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor={@name}
iframe:
    width: "550"
    height: "350"
    src: [https://embed.bsky.app/embed/did:{@did}/app.bsky.feed.post/{@id](https://embed.bsky.app/embed/did:%7B@did%7D/app.bsky.feed.post/%7B@id)}
```

Or alternatively, exported from the latest text-formatter:

```yaml
attributes:
  embedder:
    filterChain:
      - "#regexp(/^(?:[-\\w]*\\.)*bsky\\.app$/)"
    required: 1
  url:
    filterChain:
      - urldecode
      - "#regexp(/^at:\\/\\/[.:\\w]+\\/[.\\w]+\\/\\w+$/)"
    required: 1
example:
  - "https://bsky.app/profile/bsky.app/post/3kkrqzuydho2v"
  - "https://bsky.app/profile/bnewbold.net/post/3kxjq2auebs2f"
extract:
  - "#https://(?'embedder'[.\\w]+)/oembed.*?url=(?'url'[\\w%.]+)#"
helper: "s9e\\TextFormatter\\Plugins\\MediaEmbed\\Configurator\\SiteHelpers\\BlueskyHelper"
homepage: "https://bsky.app/"
host:
  - "bsky.app"
iframe:
  data-s9e-livepreview-ignore-attrs: style
  height: 600
  onload: "let c=new MessageChannel;c.port1.onmessage=e=>this.style.height=e.data+'px';this.contentWindow.postMessage('s9e:init','*',[c.port2])"
  src: "https://s9e.github.io/iframe/2/bluesky.min.html#<xsl:value-of select=\"@url\"/>#<xsl:value-of select=\"@embedder\"/>"
  width: 600
name: "Bluesky"
scrape:
  - extract:
      - "#https://(?'embedder'[.\\w]+)/oembed.*?url=(?'url'[\\w%.]+)#"
    match:
      - "#/profile/[^/]+/post/.#"
source: "https://embed.bsky.app/"
tags:
  - social
```

**Comment by rxu** [comment]
Both don't work.
The latter produces error like
I'm getting this
`Fatal error: Uncaught RuntimeException: Regexp filter is missing a 'regexp' value in ...`.

**Comment by JoshyPHP** [comment]
Yeah, it seems that version doesn't support custom regexps in site definitions. You could set the regexp manually after adding the site, or just remove it altogether since the library doesn't consider it unsafe.

```php
$configurator = new s9e\TextFormatter\Configurator;


$siteConfig = json_decode(<<<'JSON'
	{
		"attributes":{
			"embedder":{
				"filterChain":[
				],
				"required":true
			},
			"url":{
				"filterChain":[
					"urldecode"
				],
				"required":true
			}
		},
		"example":[
			"https:\/\/bsky.app\/profile\/bsky.app\/post\/3kkrqzuydho2v",
			"https:\/\/bsky.app\/profile\/jamesgunn.bsky.social\/post\/3l6kscjixz22q"
		],
		"extract":[
			"#https:\/\/(?'embedder'[.\\w]+)\/oembed.*?url=(?'url'[\\w%.]+)#"
		],
		"helper":"s9e\\TextFormatter\\Plugins\\MediaEmbed\\Configurator\\SiteHelpers\\BlueskyHelper",
		"homepage":"https:\/\/bsky.app\/",
		"host":[
			"bsky.app"
		],
		"iframe":{
			"data-s9e-livepreview-ignore-attrs":"style",
			"height":600,
			"onload":"let c=new MessageChannel;c.port1.onmessage=e=>this.style.height=e.data+'px';this.contentWindow.postMessage('s9e:init','*',[c.port2])",
			"src":"https:\/\/s9e.github.io\/iframe\/2\/bluesky.min.html#<xsl:value-of select=\"@url\"\/>#<xsl:value-of select=\"@embedder\"\/>",
			"width":600
		},
		"name":"Bluesky",
		"scrape":[
			{
				"extract":[
					"#https:\/\/(?'embedder'[.\\w]+)\/oembed.*?url=(?'url'[\\w%.]+)#"
				],
				"match":[
					"#\/profile\/[^\/]+\/post\/.#"
				]
			}
		],
		"source":"https:\/\/embed.bsky.app\/",
		"tags":[
			"social"
		]
	}
JSON, true);

$configurator->MediaEmbed->add('bluesky', $siteConfig);

extract($configurator->finalize());

$text = 'https://bsky.app/profile/bsky.app/post/3kkrqzuydho2v';
$xml  = $parser->parse($text);
$html = $renderer->render($xml);

die("$html\n");
```

**Comment by rxu** [comment]
Thanks for the hint. With this code
```yaml
attributes:
    embedder:
        required: true
    url:
        required: true
example:
    - "https://bsky.app/profile/bsky.app/post/3kkrqzuydho2v"
    - "https://bsky.app/profile/bnewbold.net/post/3kxjq2auebs2f"
extract: "#https://(?'embedder'[.\\w]+)/oembed.*?url=(?'url'[\\w%.]+)#"
homepage: "https://bsky.app/"
host: "bsky.app"
iframe:
    data-s9e-livepreview-ignore-attrs: style
    height: 600
    onload: "let c=new MessageChannel;c.port1.onmessage=e=>this.style.height=e.data+'px';this.contentWindow.postMessage('s9e:init','*',[c.port2])"
    src: "https://s9e.github.io/iframe/2/bluesky.min.html#<xsl:value-of select=\"@url\"/>#<xsl:value-of select=\"@embedder\"/>"
    width: 600
name: "Bluesky"
scrape:
    extract: "#https://(?'embedder'[.\\w]+)/oembed.*?url=(?'url'[\\w%.]+)#"
    match: "#/profile/[^/]+/post/.#"
source: "https://embed.bsky.app/"
tags:
    - social

```

there're no errors, but example URLs don't load (loads ok directly in a browser).
![image](https://github.com/user-attachments/assets/4edff49c-52aa-4475-8c96-3e5be68cddee)


The relevant source code is:
```html
<div class="content"><iframe data-s9e-mediaembed="bluesky" allowfullscreen="" loading="lazy" onload="let c=new MessageChannel;c.port1.onmessage=e=>this.style.height=e.data+'px';this.contentWindow.postMessage('s9e:init','*',[c.port2])" scrolling="no" src="https://s9e.github.io/iframe/2/bluesky.min.html#at%3A%2F%2Fdid%3Aplc%3A44ybard66vv44zksje25o7dz%2Fapp.bsky.feed.post%2F3kxjq2auebs2f#embed.bsky.app" style="border:0;height:600px;max-width:600px;width:100%"></iframe></div>

#document(https://s9e.github.io/iframe/2/bluesky.min.html#at%3A%2F%2Fdid%3Aplc%3A44ybard66vv44zksje25o7dz%2Fapp.bsky.feed.post%2F3kxjq2auebs2f#embed.bsky.app)

<html><head><title>Content from Bluesky</title><style>body{margin:0}iframe{border:0;height:100vh;width:100%}</style><script>((e,c)=>{c.onload=()=>{let b=e.createElement('iframe'),d;c.onmessage=a=>{if('s9e:init'!==a.data||d)a.source===b.contentWindow&&+a.data.height&&d.postMessage(+a.data.height);else if(d=a.ports[0],a=/^#at:\/(\/[\w.:]+\/[\w.:]+\/[\w.:]+)(?:#([.\w]+))?$/.exec(c.location.hash))b.loading='eager',b.scrolling='no',b.src='//'+(a[2]||'embed.bsky.app')+'/embed'+a[1]+'?id=0',e.body.append(b)}}})(document,window)</script></head><body></body></html>

```

**Comment by JoshyPHP** [comment]
I suspect you removed the `#urldecode` filter from the site's definition.

**Comment by rxu** [comment]
> I suspect you removed the `#urldecode` filter from the site's definition.

Indeed, thanks again. Now the code worked is:

```yaml
attributes:
    embedder:
        filterChain: []
        required: true
    url:
        filterChain: "urldecode"
        required: true
example:
    - "https://bsky.app/profile/bsky.app/post/3kkrqzuydho2v"
    - "https://bsky.app/profile/bnewbold.net/post/3kxjq2auebs2f"
extract: "#https://(?'embedder'[.\\w]+)/oembed.*?url=(?'url'[\\w%.]+)#"
homepage: "https://bsky.app/"
host: "bsky.app"
iframe:
    data-s9e-livepreview-ignore-attrs: style
    height: 600
    onload: "let c=new MessageChannel;c.port1.onmessage=e=>this.style.height=e.data+'px';this.contentWindow.postMessage('s9e:init','*',[c.port2])"
    src: "https://s9e.github.io/iframe/2/bluesky.min.html#<xsl:value-of select=\"@url\"/>#<xsl:value-of select=\"@embedder\"/>"
    width: 600
name: "Bluesky"
scrape:
    extract: "#https://(?'embedder'[.\\w]+)/oembed.*?url=(?'url'[\\w%.]+)#"
    match: "#/profile/[^/]+/post/.#"
source: "https://embed.bsky.app/"
tags: "social"
```
